default value of context as empty string rather than empty array
nelmio/NelmioJsLoggerBundle pull request #45
Opened 2022-03-24 15:44 UTC by gavinerickson

2022-03-24 16:31 UTC, gavinerickson commented
Thanks for the tip, have corrected

2022-05-04 17:01 UTC, stof requested changes
This change requires bumping the min version of symfony/http-foundation to 5.3, which is the first version support calling `all` with an argument.

2022-05-04 17:01 UTC, stof commented on Controller/LogController.php
> +            $context = (array) $request->query->all('context', array());
the code should be simplified:

- `all` does not have a second argument (the default value is always an array
- the array cast is useless

2022-08-05 10:48 UTC, Seldaek commented
Thanks, this was fixed by #47 tho so closing

2022-08-05 10:48 UTC, closed without merging